### ISSUE TITLE
Extreme Lag in Certain Areas (Quake 2)

### ISSUE THREAD

**Issue by TheOneWhoAfksInTDS** [GMH-Code/Quake2-WASM#1] opened 2024-02-18 18:21 UTC
In areas like the broken bridge in the second level, fps drops dramatically. Is it a bug or do I need to do something?

**Comment by GMH-Code** [comment] 2024-02-19 11:41
Nice to see you're trying it out!

I'll take a look and run some benchmarks around that area, and take a look at RAM/GPU use at the time.  At the moment, I am not sure of the exact cause.

I had playtested nearly all the levels at max settings (albeit doing a speedrun, including the secrets I remember), and didn't notice any lags.  In fact, getting >500FPS was common when testing on a low-end PC, and I'd maxed out the video settings.  I'd also tried it on things like a TV stick and mini keyboard, and it was still playable, but I have not tried the area you mentioned yet.

If I remember rightly, your device had a good enough CPU, and the Quake2-WASM code isn't very CPU demanding, even in WebAssembly.  It may be that the GPU is struggling to keep up with the newer rendering engine.  If memory was low then you would likely have lag in many other locations, but that is still a possibility because Quake2-WASM uses about 3 times as much of it for the full game (about 450MB vs 150MB)!

What I will say is Quake2-WASM allows you to change the video settings on the fly, so try turning off anisotropic filtering or multisampling, and try altering the resolution.  You could also try some of the Quake 2 console commands.  Ensure you're running in OpenGL ES 3 mode too -- software mode can be slow at high resolutions, but there's another thing you *may* want to try.  You will need to restart the game to do this.

A bit of background on this, and why this issue may be hard to resolve:

Quake-WASM is fast on nearly every system out there because I was able to keep nearly all of id's code intact, instead of basing my code off one of the many third-party ports which alter features, graphics, or limits.  This made the port harder, and stuff like the software renderer broke due to the new rendering environment, but I was able to repair it in a reasonable time.  My point is, this means limitations remain exactly the same as back in the day.  That means it's great even with the browser overhead.

Quake2-WASM is based off Yamagi Quake II, because it simply wasn't feasible for me to fix all the problems in the original code for Quake 2.  I did try and it was taking too long by myself.  Yamagi Quake II was far easier to port -- it was working out 'how' to do it which was the most difficult part.

Yamagi's had a lot of improvements, but those improvements were designed for powerful systems and weren't really designed with a web browser in mind.

Anyway, the bonus with Quake2-WASM being based off Yamagi is that you get a modern rendering system and the ability to alter the video settings, which is exactly what I suggest you try.

**Comment by GMH-Code** [comment] 2024-02-20 12:41
Hi @TheOneWhoAfksInTDS

I can't reproduce any unusual usage or lags in that area, no matter what hardware I try on.   There is an FPS drop due to the on-screen detail, but nothing too out of the ordinary.  I didn't notice any huge resource spikes.

I've tried on some very limited hardware which *apparently* supported WebGL 2, but it actually turned out to be faster to use software rendering mode.  I have a feeling this is because WebGL was using software emulation, and that's likely to be slower than using the software renderer.

As you've got a fast CPU, maybe try either OpenGL 1.x mode (translated to WebGL 1) or software mode?  I understand these don't look as pretty, though.

**Comment by TheOneWhoAfksInTDS** [comment] 2024-02-21 18:11
I have tried using these options but the only real decent option was forcing software rendering, which, while making the FPS in those areas better, lowers the overall fps. It might be how absolutely garbage a chromebook is though 😅

**Comment by GMH-Code** [comment] 2024-02-21 19:36
I thought that might be the case!  Thanks for trying anyway.  The Chromebook might not have much horsepower, but it should still run the game just fine.

For now I think Chrome's just not calling the game code often enough.  Like most webpages out there, Quake2-WASM doesn't actually run constantly, otherwise you get a hung tab warning.  The game relies on the browser calling it frequently.  This is usually at 60FPS, but it tries to match your host system's display VSync rate.  In my tests Chrome was failing to call the game frequently enough after a high-load situation.  Why this is, I don't know yet, but I don't see the same problem in Firefox.

The game, nor the browser, nor the host system, show high load whilst it is happening, so maybe Chrome has some code to reduce JavaScript calls under certain circumstances.  It may be down to garbage collection occuring at that point, or maybe some other intentional behaviour to protect the tab against becoming unresponsive.  Just because a tab's only using 20% of the host CPU, doesn't mean the tab is running well.  If the tab's JavaScript code is only called by Chrome 10 times a second when it wants 60, then of course it'll use less host time.

What I may try sometime is taking off the frame limiter in the game and changing browser settings to remove other limits -- something I did with Quake 1.  Playing this way is not ideal because it comes with the loss of VSync, visual tearing, a much higher load on the browser, and a hotter computer.  If I remember I also had to change some browser settings to remove some other limits.  It'll be interesting to see if the problem remains after that.

Until I have chance to have a further look, I hope you can enjoy the game as-is!

**Comment by GMH-Code** [comment] 2024-02-23 14:47
I think I've found the problem.  It seems like you've found something interesting outside of the game, either in the Emscripten runtime or the plugins.  It looks like my timing mode (what locks the game to 60FPS or your VSync rate) is being ignored.

What this means is the tab is using all the available load.  The browser, however, is not allowing the tab to claim high load reliably.  This would explain the lags, despite having low CPU time on the tab.

The odd thing is, if I attempt to reduce the load on the tab, the game runs at full speed regardless.  No adjustments to the timing mechanism make any difference.  This just shouldn't happen -- it works fine in Quake-WASM.

In my mostly-raw Quake 1 port, if you pull down the console and run this:
```
timedemo demo1
```

The demo will run really smoothly, but the playback is accelerated.  At the report stage, you'll usually get a 'perfect' 60.0FPS, with 969 frames in 16.2 seconds.  This is what's meant to happen, and it's one of the reasons why the port runs so well and is responsive.

In the Quake 2 port, try this in the console (must be on separate lines, not semicolon separated):
```
timedemo 1
map demo1.dm2
timedemo 0
```

This goes crazy and finishes the demo in seconds, well in excess of 60FPS.  The report also has much higher variance over multiple runs.  This means the cap isn't working.

I've tried changing the timing mode of the game to everything that's available.  I've also tried restricting it to 10FPS, so I can visually see it being throttled, but -- nope, it still runs above 60FPS.

I'll see if I can work out where the problem is.

**Comment by GMH-Code** [comment] 2024-02-23 15:09
Well, that was an awkward one to fix!

So it turns out the timing mode appears to be reset after video (renderer) initialisation.  This unwanted adjustment appears to either be within Emscripten's code, or with one of the many modules it comes with.  As it doesn't happen in Quake-WASM, I suspect this is something to do with when the OpenGL ES 3 / WebGL 2 renderer is initialised.  I'm quite sure the issue is not in Quake2-WASM, though.

I have put a check in place to see whether the timing mode has been altered after video and map startup.  It if has been, the correct timing method will be re-applied before the game starts drawing frames.

Hopefully this fixes it and sorts your timing/lag issue.  By the way, if you have chance (and don't feel at all obliged to), a star on the Quake projects you play would be much appreciated.

Running the benchmark in Quake 2 now shows the expected 60FPS, which is the (usual) rate the browser should call the game.

Let me know if it worked!

**Comment by GMH-Code** [comment] 2024-03-20 15:19
Permanent fixes for this issue have been applied which supersede the above.  Closing as done.

**Closed by GMH-Code** 2024-03-20 15:19 UTC
